version: '3.9'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_PASSWORD=password
      - MARIADB_USER=user